//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballShopModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int id { get; set; }
        public Nullable<int> accountId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> totalPrice { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual BillDetail BillDetail { get; set; }
    }
}
